#!/bin/sh

mkdir -p ipkg/home/retrofw/games/opentyrian
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/games
cp opentyrian ipkg/home/retrofw/games/opentyrian/opentyrian
cp -r ./data ipkg/home/retrofw/games/opentyrian
cp tyrian.png ipkg/home/retrofw/games/opentyrian/opentyrian.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: opentyrian
Version: 20190303
Description: Schmup game
Section: games
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/opentyrian
Depends:
Source: https://github.com/gameblabla/opentyrian' > control

print '2.0' > debian-binary

print 'title=OpenTyrian
description=Schmup game
exec=/home/retrofw/games/opentyrian/opentyrian
clock=600
' > home/retrofw/apps/gmenu2x/sections/games/opentyrian

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../opentyrian.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
